config/routes.rb
Rails.application.routes.draw do
  resources :menus
  resources :restaurants
  resources :employees
  get 'random_lunch', to: 'lunch#random_lunch'
  get 'paid_lunch', to: 'lunch#paid_lunch'
  post 'create_random_lunch', to: 'lunch#create_random_lunch'
  post 'create_paid_lunch', to: 'lunch#create_paid_lunch'
  root 'lunch#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :menus, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.page(params[:page]).per(10)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :address, :preference)
    end
end

app/controllers/lunch_controller.rb
class LunchController < ApplicationController
  before_action :set_employees, only: [:random_lunch, :paid_lunch]

  def index; end

  def random_lunch; end

  def create_random_lunch
    selected_employees_id = random_lunch_params['employee_ids'].map(&:to_i)
    @employees = Employee.where(id: selected_employees_id)
    @selected_restaurants = FindRestaurantService.new(selected_employees_id)
                            .fetch_restaurants
    if @selected_restaurants.blank?
      redirect_to random_lunch_path, notice: 'No restaurant meet the crietria'
    end
  end

  def paid_lunch; end


  def create_paid_lunch
    employee_ids = paid_lunch_params['employee_ids'].map(&:to_i)
    restaurant_ids  = FindRestaurantService.new(employee_ids)
                       .fetch_restaurants
                       .pluck(:id)
    if restaurant_ids.present?
      @menu = FetchMenuService.new({
                restaurant_ids: restaurant_ids,
                employee_ids: employee_ids,
                price: paid_lunch_params[:price]
              }).fetch_menu_for_restaurants
    end
    puts "menu is #{@menu}"
    if restaurant_ids.blank? || @menu.blank?
      redirect_to paid_lunch_path, notice: 'No restaurant meet the crietria.'
    end
  end

  private

  def set_employees
    @employees = Employee.all
  end

  def paid_lunch_params
    params.permit(:price, employee_ids: [])
  end

  def random_lunch_params
    params.permit(employee_ids: [])
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:restaurant_id, :name, :price, :tag)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/lunch_helper.rb
module LunchHelper
  def fetch_restaurant(restaurant_id)
    Restaurant.find(restaurant_id)
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :employee_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :employee_address %>
  </div>

  <div class="field">
    <%= form.label :preference %>
    <%= form.text_field :preference, id: :employee_preference %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Preference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.address %></td>
        <td><%= employee.preference %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @employees %>

<br>

<%= link_to 'New Employee', new_employee_path %>

<br>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>Preference:</strong>
  <%= @employee.preference %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealDelivery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= link_to 'Home', root_path %>
  </body>
</html>

app/views/lunch/create_paid_lunch.html.erb
<h1>Paid Lunch</h1>

<h3>Suggested Restaurant for paid Lunch</h3>

<% @menu.each do  |restaurant_id, menu|%>
  <% restaurant = fetch_restaurant(restaurant_id) %>
  <h4>Restaurant details</h4>
  <%= "Id: #{restaurant.id}" %>
  <br>
  <%= "Name: #{restaurant.name}" %>
  <br>
  <%= "Address: #{restaurant.address}" %>
  <br>
  <p> selected menu for the restaurant</p>
  <table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Tag</th>
        <th>Price</th>
        <th colspan="5"></th>
      </tr>
    </thead>

    <tbody>
      <% menu.each do |m| %>
        <tr>
          <td><%= m.id %></td>
          <td><%= m.name %></td>
          <td><%= m.tag %></td>
          <td><%= m.price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/lunch/create_random_lunch.html.erb
<h1>Random Lunch</h1>

<h3>Suggested Restaurant for random Lunch</h3>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Address</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @selected_restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.id %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h4>Selected Employee</h4>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Preference</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.address %></td>
        <td><%= employee.preference %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lunch/index.html.erb
<h1>Meal Delivery System</h1>

<%= link_to 'View Employee', employees_path %>
<br>
<%= link_to 'View Restaurants', restaurants_path %>
<br>
<%= link_to 'View Menu', menus_path %>
<br>
<%= link_to 'Create Random Lunch', random_lunch_path %>
<br>
<%= link_to 'Create Paid Lunch', paid_lunch_path %>
<br>

app/views/lunch/paid_lunch.html.erb
<p id="notice"><%= notice %></p>

<h1>Paid Lunch</h1>

<%= form_with(url: create_paid_lunch_path, local: true) do |form| %>
  <table>
    <thead>
      <tr>
        <th>Select Employee</th>
        <th>Name</th>
        <th>Address</th>
        <th>Preference</th>
        <th colspan="5"></th>
      </tr>
    </thead>

    <tbody>
        <% @employees.each do |employee| %>
          <tr>
            <td><%= check_box_tag('employee_ids[]', employee.id) %></td>
            <td><%= employee.name %></td>
            <td><%= employee.address %></td>
            <td><%= employee.preference %></td>
            <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
          </tr>
        <% end %>
        <label>Price</label>
        <%= form.number_field :price%>
        <br>
        <br>
    </tbody>
  </table>
  <%= form.submit %>
<% end %>
<br>

app/views/lunch/random_lunch.html.erb
<p id="notice"><%= notice %></p>

<h1>Random Lunch</h1>

<%= form_with(url: create_random_lunch_path, local: true) do |form| %>
  <table>
    <thead>
      <tr>
        <th>Select Employee</th>
        <th>Name</th>
        <th>Address</th>
        <th>Preference</th>
        <th colspan="5"></th>
      </tr>
    </thead>

    <tbody>
        <% @employees.each do |employee| %>
          <tr>
            <td><%= check_box_tag('employee_ids[]', employee.id) %></td>
            <td><%= employee.name %></td>
            <td><%= employee.address %></td>
            <td><%= employee.preference %></td>
            <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
          </tr>
        <% end %>
    </tbody>
  </table>
  <%= form.submit %>
<% end %>

<br>

app/views/meals/index.html.erb
<h1>Meal Delivery System</h1>

<%= link_to 'View Employee', employees_path %>
<br>
<%= link_to 'View Restaurants', restaurants_path %>

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :restaurant_id %>
    <%= form.collection_select(:restaurant_id, Restaurant.all, :id, :name, :prompt => 'Select')%>
    <br>
    <%= form.label :name%>
    <%= form.text_field :name, id: :menu_name %>
    <br>
    <%= form.label :price %>
    <%= form.number_field :price, id: :menu_price %>
    <br>
    <%= form.label :tag %>
    <%= form.text_field :tag, id: :menu_tag%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menus</h1>

<table>
  <thead>
    <tr>
      <th>Restaurant</th>
      <th>Name</th>
      <th>Price</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.restaurant.name %></td>
        <td><%= menu.name %></td>
        <td><%= menu.price %></td>
        <td><%= menu.tag %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Restaurant:</strong>
  <%= @menu.restaurant.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu.price %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @menu.tag %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :restaurant_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :restaurant_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @restaurants %>
<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

<br>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>